### PR TITLE
Change PyPI name from 'cuid.py' to just 'cuid' (#9)

### PR DESCRIPTION
**Pull request by notpushkin**
I've changed the name in setup.py. I've also uploaded the changed version to PyPI (both sdist and wheel) and added you as an Owner.

### CODE REVIEW

**Comment by notpushkin** [comment]
I haven't tested the Conda recipe though :V

**Comment by necaris** [comment]
@iamale looking at it on PyPI, it looks like you're the only Owner of this?

**Comment by notpushkin** [comment]
@necaris It doesn't to me, huh:

screenshot_2017-10-27_23-11-46

**Comment by necaris** [comment]
Thank you @iamale, I figured it out! Pushed a new tag with minor Mypy improvements and to verify that the new name would work, and it did!

**Pull request merged**
