### PR TITLE
travis: Run pypy tests with 5.4

### PR DESCRIPTION
**Pull request by scop**

### CODE REVIEW

**Comment by necaris** [comment]
I don't understand why pinning to v5.4 is necessary?

**Comment by scop** [comment]
Pinning like this is unfortunately the only way at the moment to get a current pypy on Travis, until they update their defaults. Their default is old and less relevant than the current 5.4(.x) version.

**Comment by necaris** [comment]
Will that work consistently? [This blog post](http://jhshi.me/2016/10/03/tox-and-travis-setup-for-pypy-project/index.html) indicates that more manual steps are required to install the latest PyPy.

**Comment by necaris** [comment]
Instead of replacing the `pypy` key, can we simply add the `pypy-5.4` key, then? Can we do something similar for the `pypy3` version, since I know 5.5 is out for that too?

**Comment by scop** [comment]
I'm not sure what you mean by consistently. Travis ships pypy 5.4 under the name pypy-5.4, and the ci build log shows it gets used as expected: https://travis-ci.org/necaris/cuid.py/builds/167458430
The linked blog post talks about tox and pypy 5.4**.1**, maybe that's a setup where more steps would be needed. I don't think they are needed for toxless 5.4 setup on Travis.

If you want to keep running the tests with the old pypy as well, sure, pypy-5.4 could be added instead of replacing it.

pypy3 5.5 is an alpha version, whereas the one shipped under the pypy3 name in Travis is not. Just a data point if you're considering to replace it. BTW I don't think Travis has pypy3 5.5 available yet. They do have the previous alpha (5.2): https://github.com/travis-ci/travis-ci/issues/6277

**Comment by necaris** [comment]
Closing in favor of #8, which adds rather than replaces the additional PyPy versions. Thank you @scop for the suggestion!

**Pull request closed without merging**
